AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Micronaut API - example.micronaut::prime-finder
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Resources:
  MyServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: not.used.in.provided.runtime
      Runtime: provided
      CodeUri: s3://micronaut-graal-demo/ddfed9d1d4d0edae56fcd85022187c0b
      MemorySize: 128
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
Outputs:
  MyServiceApi:
    Description: URL for application
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/find-primes-below/{number}
    Export:
      Name: MyServiceApi
